# org: minhdo714
service: pcb-scraper

useDotenv: true
provider:
  name: aws
  region: us-east-1
  architecture: x86_64
  memorySize: 2048
  timeout: 300
  profile: pcb-scraper

  environment:
    PROXY_URL: ${env:PROXY_URL}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_SERVICE_KEY}

  ecr:
    images:
      scraper-image-v14:
        path: .
        platform: linux/amd64

# plugins:
#   - serverless-lift

functions:
  scrape:
    image:
      name: scraper-image-v14
    url: true  # Enable Function URL (bypasses 29s API Gateway limit)
    events:
      - http:
          path: scrape
          method: post
